# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  showConsole: true
  htmlTemplate: ./docs/index.html
  theme:
    sidebar:
      backgroundColor: '#ffffff'
      typography:
        fontFamily: 'Roboto, sans-serif'
    colors:
      primary:
        main: "#345933"
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl # Can be one of the following supported languages: "curl", "Node.js", "JavaScript".
      - lang: "Node.js"
      - lang: "JavaScript"
      